name: cool_web_site
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_widget_from_html: ^0.16.0
  video_player: ^2.10.0
  webview_flutter_plus: ^0.4.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  youtube_player_flutter: ^8.1.1
  audioplayers: ^5.2.1

flutter:
  assets:
    - assets/music.mp4
  uses-material-design: true
